# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy remaining source code and build
COPY . .
RUN npm run build

# Set executable permission in case build/index.js lost it
RUN chmod +x build/index.js

# Default command to run the server
ENTRYPOINT ["node", "build/index.js"]
